const HOMEPAGE = 0;
const POSTPAGE = 1;
const ACCOUNTPAGE = 2;
const MESSAGEPAGE = 3;
const CONFIGURATIONPAGE = 4;

const int EVENT = 18;
const int BOOKS = 57;
const int DONATION_EXCHANGE = 54;
const int FOOD = 95;
const int JOB = 27;
const int COURSES_TRAINING = 69;

const String USER_EMAIL = "USER_EMAIL";
const String USER_NAME = "USER_NAME";
const String DEVICE_TOKEN = "DEVICE_TOKEN";
const String AUTHENTICATION_TOKEN = "auth-token";
const String NEW_MESSAGE = "NEW_MESSAGE";
const String MESSAGE_LIST = "MESSAGE_LIST";
const String MESSAGE_LIST_CACHE_TIME = "MESSAGE_LIST_CACHE_TIME";
const String POST_LIST = "POST_LIST";
const String MY_FAVORIT_LIST = "MY_FAVORIT_LIST";
const String MY_FAVORIT_LIST_CACHE_TIME = "MY_FAVORIT_LIST_CACHE_TIME";
const String MY_POST_LIST = "POST_LIST";
const String POST_LIST_CACHE_TIME = "POST_LIST_CACHE_TIME";
const String MY_POST_LIST_CACHE_TIME = "MY_POST_LIST_CACHE_TIME";
const String CATEGORIE_LIST = "CATEGORIE_LIST";
const String CATEGORIE_LIST_CACHE_TIME = "CATEGORIE_LIST_CACHE_TIME";
const String PARENT_CATEGORIE_LIST = "PARENT_CATEGORIE_LIST";
const String SHOW_PICTURES = "SHOW_PICTURES";
const String SHOW_PICTURES_YES = "SHOW_PICTURES_YES";
const String SHOW_PICTURES_NO = "SHOW_PICTURES_NO";

final int MAX_RATING = 5;

final String SERVER_KEY =
    "AAAA3RFWb2g:APA91bHZ8ZgSyvEpVclsAjKmLjUndGnuQK4ZK6302Anw3Vfout-Ffb7s2Xum8wGSiZi0xlOE8v1Y9bZ9gZDyocYe7a4-nNSpk7FcSvmO4Z52rfCpMJR_sFdO2yWeo8NKhKHtbYMIGOQg";
final String GOOGLE_FCM_END_POINT = 'https://fcm.googleapis.com/fcm/send';
